# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('isDefault', models.BooleanField(default=1)),
                ('title', models.CharField(max_length=80)),
                ('order', models.IntegerField(default=0, blank=True)),
                ('forum', models.CharField(default=b'general', max_length=80)),
            ],
            options={
                'ordering': ['order'],
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('name', models.CharField(unique=True, max_length=80, verbose_name='Name')),
                ('url', models.URLField(max_length=300, verbose_name='Website URL', blank=True)),
                ('language', models.CharField(default=b'en', max_length=3, choices=[(b'en', b'English'), (b'te', b'Telugu'), (b'AS', b'Assamese'), (b'HI', b'Hindi'), (b'kok', b'Konkani'), (b'GU', b'Gujarati'), (b'UR', b'Urdu'), (b'kn', b'Kannada'), (b'mal', b'Malayalam'), (b'mr', b'Marathi'), (b'mni', b'Manipuri'), (b'OR', b'Oriya'), (b'PA', b'Punjabi'), (b'ne', b'Nepali'), (b'ta', b'Tamil'), (b'BN', b'Bengali')])),
                ('description', models.TextField(verbose_name='Description', blank=True)),
                ('guidelines', models.CharField(max_length=200, null=True, blank=True)),
                ('favicon', models.CharField(max_length=200, null=True, blank=True)),
                ('avatar', models.CharField(max_length=200, null=True, blank=True)),
                ('signedUrl', models.CharField(max_length=200, null=True, blank=True)),
                ('raw_guidelines', models.CharField(max_length=200, null=True, blank=True)),
                ('channel', models.CharField(max_length=200, null=True, blank=True)),
                ('createdAt', models.DateTimeField(null=True, verbose_name='Date', blank=True)),
                ('category', models.ForeignKey(related_name='forum_category', to='reflect.Category')),
                ('founder', models.ForeignKey(related_name='founder', verbose_name='Founder', to=settings.AUTH_USER_MODEL)),
                ('moderators', models.ForeignKey(verbose_name='Moderators', blank=True, to=settings.AUTH_USER_MODEL, null=True)),
            ],
            options={
                'ordering': ['category'],
                'verbose_name': 'Forum',
                'verbose_name_plural': 'Forums',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('isJuliaFlagged', models.BooleanField(default=False)),
                ('isFlagged', models.BooleanField(default=False)),
                ('parent', models.IntegerField(default=0)),
                ('isDeleted', models.BooleanField(default=False, help_text='Check this box if the comment is inappropriate. A "This comment has been removed" message will be displayed instead.', verbose_name='is removed')),
                ('isApproved', models.BooleanField(default=True)),
                ('createdAt', models.DateTimeField(default=None, verbose_name='date/time submitted')),
                ('numReports', models.IntegerField(default=0)),
                ('isEdited', models.BooleanField(default=False)),
                ('message', models.TextField(max_length=3000, verbose_name='Description')),
                ('isSpam', models.BooleanField(default=False)),
                ('isHighlighted', models.BooleanField(default=False)),
                ('ip_address', models.GenericIPAddressField(unpack_ipv4=True, null=True, verbose_name='IP address', blank=True)),
                ('is_public', models.BooleanField(default=True, help_text='Uncheck this box to make the comment effectively disappear from the site.', verbose_name='is public')),
                ('tree_path', models.CharField(verbose_name='Tree path', max_length=500, editable=False)),
                ('media', models.CharField(max_length=20, null=True, blank=True)),
                ('points', models.IntegerField(default=0)),
                ('dislikes', models.IntegerField(default=0)),
                ('likes', models.IntegerField(default=0)),
                ('raw_message', models.CharField(max_length=2000, null=True, blank=True)),
                ('isDeletedByAuthor', models.BooleanField(default=False)),
                ('author', models.ForeignKey(related_name='comments_author', verbose_name='User', to=settings.AUTH_USER_MODEL)),
                ('forum', models.ForeignKey(related_name='comments', verbose_name='Forum', to='reflect.Forum')),
                ('last_child', models.ForeignKey(on_delete=django.db.models.deletion.SET_NULL, verbose_name='Last child', blank=True, to='reflect.Post', null=True)),
            ],
            options={
                'ordering': ['createdAt'],
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('title', models.CharField(max_length=80)),
                ('supportLevel', models.IntegerField(default=0, blank=True)),
                ('adsDRNativeEnabled', models.BooleanField(default=0)),
                ('adsBannerEnabled', models.BooleanField(default=0)),
                ('disable3rdPartyTrackers', models.BooleanField(default=0)),
                ('adsVideoEnabled', models.BooleanField(default=0)),
                ('allowMedia', models.BooleanField(default=0)),
                ('allowAnonPost', models.BooleanField(default=0)),
                ('allowAnonVotes', models.BooleanField(default=0)),
                ('ssoRequired', models.BooleanField(default=0)),
                ('mustVerify', models.BooleanField(default=0)),
                ('discoveryLocked', models.BooleanField(default=0)),
                ('audienceSyncEnabled', models.BooleanField(default=0)),
                ('hasCustomAvatar', models.BooleanField(default=0)),
                ('isVIP', models.BooleanField(default=0)),
                ('mustVerifyEmail', models.BooleanField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('url', models.URLField(unique=True, max_length=500, verbose_name='URL')),
                ('documentTitle', models.CharField(max_length=80, verbose_name='Document Title')),
                ('sortOrder', models.IntegerField()),
                ('language', models.CharField(default=b'en', max_length=3, choices=[(b'en', b'English'), (b'te', b'Telugu'), (b'AS', b'Assamese'), (b'HI', b'Hindi'), (b'kok', b'Konkani'), (b'GU', b'Gujarati'), (b'UR', b'Urdu'), (b'kn', b'Kannada'), (b'mal', b'Malayalam'), (b'mr', b'Marathi'), (b'mni', b'Manipuri'), (b'OR', b'Oriya'), (b'PA', b'Punjabi'), (b'ne', b'Nepali'), (b'ta', b'Tamil'), (b'BN', b'Bengali')])),
                ('feed', models.CharField(max_length=255, null=True, blank=True)),
                ('uploadAdd', models.CharField(max_length=255, null=True, blank=True)),
                ('dislikes', models.IntegerField(default=0)),
                ('likes', models.IntegerField(default=0)),
                ('message', models.CharField(max_length=100, null=True, verbose_name='Message to users', blank=True)),
                ('canModerate', models.BooleanField(default=False, verbose_name='Moderate')),
                ('canPost', models.BooleanField(default=False)),
                ('createdAt', models.DateTimeField(verbose_name='Date')),
                ('category', models.IntegerField(default=0)),
                ('clean_title', models.CharField(max_length=255, null=True, blank=True)),
                ('userScore', models.IntegerField(default=0)),
                ('isSpam', models.BooleanField(default=False)),
                ('signedLink', models.CharField(max_length=255, null=True, blank=True)),
                ('isDeleted', models.BooleanField(default=False, verbose_name='Delete Thread')),
                ('hasStreaming', models.BooleanField(default=False)),
                ('uploadRemove', models.CharField(max_length=255, null=True, blank=True)),
                ('raw_message', models.CharField(max_length=255, null=True, blank=True)),
                ('isClosed', models.BooleanField(default=False)),
                ('link', models.CharField(unique=True, max_length=200, verbose_name='Link')),
                ('slug', models.SlugField(max_length=100)),
                ('identifiers', models.CharField(max_length=500)),
                ('posts', models.IntegerField(default=0)),
                ('userSubscription', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=80, verbose_name='Title')),
                ('highlightedPost', models.BooleanField(default=False)),
                ('id_attachment', models.CharField(max_length=200, null=True, blank=True)),
                ('id', models.AutoField(serialize=False, primary_key=True)),
                ('reactions', models.IntegerField(default=0)),
                ('author', models.ForeignKey(related_name='Thread_author', verbose_name='User', to=settings.AUTH_USER_MODEL)),
                ('forum', models.ForeignKey(related_name='thread_foru', verbose_name='Forum', to='reflect.Forum')),
                ('moderators', models.ForeignKey(related_name='Thread_', verbose_name='User', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['forum', 'createdAt', 'title'],
                'verbose_name': 'Thread',
                'verbose_name_plural': 'Threads',
            },
        ),
        migrations.AddField(
            model_name='post',
            name='thread',
            field=models.ForeignKey(related_name='comments', verbose_name='Thread', to='reflect.Thread'),
        ),
        migrations.AddField(
            model_name='forum',
            name='settings',
            field=models.ForeignKey(related_name='settings', verbose_name='settings', to='reflect.Settings'),
        ),
    ]
